# Generated by Django 2.2.3 on 2021-04-07 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('teamName', models.CharField(max_length=30, null=True, verbose_name='teamName')),
                ('M1MailId', models.EmailField(max_length=30, primary_key=True, serialize=False, verbose_name='M1MailId')),
                ('M1Name', models.CharField(max_length=30, null=True, verbose_name='M1Name')),
                ('M1College', models.CharField(max_length=30, null=True, verbose_name='M1College')),
                ('M1Phone', models.CharField(max_length=15, null=True, verbose_name='M1Phone')),
                ('M2MailId', models.EmailField(max_length=30, null=True, verbose_name='M2MailId')),
                ('M2Name', models.CharField(max_length=30, null=True, verbose_name='M2Name')),
                ('M2College', models.CharField(max_length=30, null=True, verbose_name='M2College')),
                ('M2Phone', models.CharField(max_length=15, null=True, verbose_name='M2Phone')),
                ('M3MailId', models.EmailField(max_length=30, null=True, verbose_name='M3MailId')),
                ('M3Name', models.CharField(max_length=30, null=True, verbose_name='M3Name')),
                ('M3College', models.CharField(max_length=30, null=True, verbose_name='M3College')),
                ('M3Phone', models.CharField(max_length=15, null=True, verbose_name='M3Phone')),
                ('M4MailId', models.EmailField(max_length=20, null=True, verbose_name='M4MailId')),
                ('M4Name', models.CharField(max_length=30, null=True, verbose_name='M4Name')),
                ('M4College', models.CharField(max_length=30, null=True, verbose_name='M4College')),
                ('M4Phone', models.CharField(max_length=15, null=True, verbose_name='M4Phone')),
            ],
        ),
        migrations.CreateModel(
            name='domains',
            fields=[
                ('ProjectNo', models.AutoField(primary_key=True, serialize=False, verbose_name='ProjectNo')),
                ('domainName', models.CharField(max_length=30, null=True, verbose_name='domainName')),
                ('abstract', models.CharField(max_length=200, null=True, verbose_name='abstract')),
                ('M1MailId', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wieHack.participants')),
            ],
        ),
    ]
